-- ============================================================
-- Schemat bazy danych dla Budomex (wersja reaktywna - R2DBC)
-- R2DBC nie generuje DDL automatycznie (jak Hibernate ddl-auto),
-- dlatego schemat jest tworzony tym skryptem przy starcie
-- (spring.sql.init.mode=always).
-- Skladnia kompatybilna z H2 i PostgreSQL.
-- ============================================================

CREATE TABLE IF NOT EXISTS "users" (
                                       "ID"              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       "username"        VARCHAR(100)  NOT NULL UNIQUE,
    "email"           VARCHAR(255)  NOT NULL UNIQUE,
    "password"        VARCHAR(255)  NOT NULL,
    "first_name"      VARCHAR(100),
    "last_name"       VARCHAR(100),
    "phone"           VARCHAR(20),
    "role"            VARCHAR(20)   NOT NULL,
    "enabled"         BOOLEAN       NOT NULL DEFAULT TRUE,
    "created_at"      TIMESTAMP     NOT NULL,
    "updated_at"      TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS "orders" (
                                        "ID"                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        "customer_name"                   VARCHAR(200)  NOT NULL,
    "customer_email"                  VARCHAR(255)  NOT NULL,
    "customer_phone"                  VARCHAR(20),
    "customer_address"                TEXT,
    "product_type"                    VARCHAR(30)   NOT NULL,
    "product_specifications"          TEXT,
    "quantity"                        INTEGER       NOT NULL DEFAULT 1,
    "status"                          VARCHAR(30)   NOT NULL,
    "price"                           DECIMAL(10,2),
    "submission_date"                 TIMESTAMP     NOT NULL,
    "estimated_delivery_date"         DATE,
    "customer_acceptance_deadline"    TIMESTAMP,
    "customer_accepted"               BOOLEAN,
    "customer_response_date"          TIMESTAMP,
    "production_start_date"           TIMESTAMP,
    "production_end_date"             TIMESTAMP,
    "installation_date"               TIMESTAMP,
    "manager_notes"                   TEXT,
    "production_notes"                TEXT,
    "acceptance_token"                VARCHAR(255) UNIQUE,
    "reminder_sent"                   BOOLEAN       NOT NULL DEFAULT FALSE,
    "archived"                        BOOLEAN       NOT NULL DEFAULT FALSE,
    "completion_percentage"           INTEGER       NOT NULL DEFAULT 0,
    "approved_by_manager_id"          BIGINT REFERENCES "users"("ID"),
    "created_at"                      TIMESTAMP     NOT NULL,
    "updated_at"                      TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS "production_tasks" (
                                                  "ID"                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                  "order_id"          BIGINT NOT NULL REFERENCES "orders"("ID") ON DELETE CASCADE,
    "description"       VARCHAR(500) NOT NULL,
    "category"          VARCHAR(100),
    "sequence_number"   INTEGER NOT NULL DEFAULT 0,
    "completed"         BOOLEAN NOT NULL DEFAULT FALSE,
    "completed_at"      TIMESTAMP,
    "completed_by_id"   BIGINT REFERENCES "users"("ID"),
    "notes"             TEXT,
    "created_at"        TIMESTAMP NOT NULL,
    "updated_at"        TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS "order_history" (
                                               "ID"              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                               "order_id"        BIGINT NOT NULL REFERENCES "orders"("ID") ON DELETE CASCADE,
    "previous_status" VARCHAR(30),
    "new_status"      VARCHAR(30) NOT NULL,
    "changed_by_id"   BIGINT REFERENCES "users"("ID"),
    "notes"           TEXT,
    "changed_at"      TIMESTAMP NOT NULL
    );

CREATE TABLE IF NOT EXISTS "order_assigned_workers" (
                                                        "ID"        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                        "order_id"  BIGINT NOT NULL REFERENCES "orders"("ID") ON DELETE CASCADE,
    "user_id"   BIGINT NOT NULL REFERENCES "users"("ID") ON DELETE CASCADE,
    CONSTRAINT uq_order_worker UNIQUE ("order_id", "user_id")
    );

CREATE TABLE IF NOT EXISTS "inventory_items" (
                                                 "ID"                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                 "name"                VARCHAR(200) NOT NULL,
    "category"            VARCHAR(30)  NOT NULL,
    "unit"                VARCHAR(20)  NOT NULL DEFAULT 'szt.',
    "current_quantity"    INTEGER      NOT NULL DEFAULT 0,
    "reserved_quantity"   INTEGER      NOT NULL DEFAULT 0,
    "minimum_threshold"   INTEGER      NOT NULL DEFAULT 10,
    "created_at"          TIMESTAMP    NOT NULL,
    "updated_at"          TIMESTAMP
    );

CREATE INDEX IF NOT EXISTS "idx_orders_status" ON "orders"("status");
CREATE INDEX IF NOT EXISTS "idx_orders_archived" ON "orders"("archived");
CREATE INDEX IF NOT EXISTS "idx_production_tasks_order" ON "production_tasks"("order_id");
CREATE INDEX IF NOT EXISTS "idx_order_history_order" ON "order_history"("order_id");
CREATE INDEX IF NOT EXISTS "idx_order_assigned_workers_order" ON "order_assigned_workers"("order_id");
CREATE INDEX IF NOT EXISTS "idx_order_assigned_workers_user" ON "order_assigned_workers"("user_id");